server:
  port: 8090

spring:
  application:
    name: ms-api-gateway

  config:
    import: "optional:configserver:http://config-server:8888"

  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://ms-customer
          predicates:
            - Path=/api/customers/**
        - id: products
          uri: lb://ms-products
          predicates:
            - Path=/api/products/**
        - id: transactions
          uri: lb://ms-transactions
          predicates:
            - Path=/api/transactions/**
        - id: movements
          uri: lb://ms-movements
          predicates:
            - Path=/api/movements/**

  data:
    mongodb:
      uri: mongodb+srv://rodasenoc4_db_user:LVDqpURVaOZbfkQz@nnt-distributed-db.effpohk.mongodb.net/nnt-db?retryWrites=true&w=majority&appName=nnt-distributed-db

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

app:
  jwt:
    secret: "miclavesecretamuyseguraymuylarga12345678901234567890"
    expirationMs: 3600000 # 1h
