server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-api-gateway
  data:
    mongodb:
      uri: mongodb+srv://rodasenoc4_db_user:LVDqpURVaOZbfkQz@nnt-distributed-db.effpohk.mongodb.net/nnt-db?retryWrites=true&w=majority&appName=nnt-distributed-db
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/api/customers/**
        - id: products
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: transactions
          uri: http://localhost:8181
          predicates:
            - Path=/api/transactions/**
        - id: movements
          uri: http://localhost:8084
          predicates:
            - Path=/api/movements/**

app:
  jwt:
    secret: "miclavesecretamuyseguraymuylarga12345678901234567890"
    expirationMs: 3600000 # 1h
