server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: ms-api-gateway
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://ms-customer:8081
          predicates:
            - Path=/api/customers/**
        - id: products
          uri: http://ms-products:8082
          predicates:
            - Path=/api/products/**
        - id: transactions
          uri: http://ms-transactions:8181
          predicates:
            - Path=/api/transactions/**
        - id: movements
          uri: http://ms-movements:8084
          predicates:
            - Path=/api/movements/**

  data:
    mongodb:
      uri: mongodb+srv://rodasenoc4_db_user:LVDqpURVaOZbfkQz@nnt-distributed-db.effpohk.mongodb.net/nnt-db?retryWrites=true&w=majority&appName=nnt-distributed-db

app:
  jwt:
    secret: "miclavesecretamuyseguraymuylarga12345678901234567890"
    expirationMs: 3600000 # 1h
