server:
  port: 8090
  
spring:
  application:
    name: ms-api-gateway
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081
          predicates:
            - Path=/api/customers/**
        - id: products
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
        - id: transactions
          uri: http://localhost:8181
          predicates:
            - Path=/api/transactions/**
        - id: movements
          uri: http://localhost:8084
          predicates:
            - Path=/api/movements/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: "miclavesecretamuyseguraymuylarga12345678901234567890"
    expirationMs: 3600000 # 1h
