server:
  port: 8080

spring:
  application:
    name: ms-api-gateway

  cloud:
    config:
      import: "optional:configserver:http://config-server:8888"

    gateway:
      routes:
        - id: customer
          uri: http://ms-customer:8081
          predicates:
            - Path=/api/customers/**
        - id: products
          uri: http://ms-products:8082
          predicates:
            - Path=/api/products/**
        - id: transactions
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=1
        - id: movements
          uri: http://ms-movements:8084
          predicates:
            - Path=/api/movements/**
        - id: wallets
          uri: http://ms-wallet:9001
          predicates:
            - Path=/api/wallets/**

  data:
    mongodb:
      uri: mongodb+srv://rodasenoc4_db_user:LVDqpURVaOZbfkQz@nnt-distributed-db.effpohk.mongodb.net/nnt-db?retryWrites=true&w=majority&appName=nnt-distributed-db

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

app:
  jwt:
    secret: "miclavesecretamuyseguraymuylarga12345678901234567890"
    expirationMs: 3600000
