server:
  port: 8080

spring:
  application:
    name: ms-api-gateway
  cloud:
    config:
      uri: http://config-server:8888
    gateway:
      routes:
        - id: customer
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: products
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: transactions
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
        - id: movements
          uri: lb://movement-service
          predicates:
            - Path=/api/movements/**
        - id: wallets
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**
  data:
    mongodb:
      uri: mongodb+srv://rodasenoc4_db_user:LVDqpURVaOZbfkQz@nnt-distributed-db.effpohk.mongodb.net/nnt-db?retryWrites=true&w=majority&appName=nnt-distributed-db
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
app:
  jwt:
    secret: "miclavesecretamuyseguraymuylarga12345678901234567890"
    expirationMs: 3600000
