server:
  port: 8084

spring:
  application:
    name: ms-movement-business

  cloud:
    config:
      uri: http://localhost:8888

  data:
    mongodb:
      uri: mongodb+srv://rodasenoc4_db_user:LVDqpURVaOZbfkQz@nnt-distributed-db.effpohk.mongodb.net/nnt-db?retryWrites=true&w=majority&appName=nnt-distributed-db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka