server:
  port: 9002

spring:
  application:
    name: ms-transaction-processor

  cloud:
    config:
      import: "optional:configserver:http://config-server:8888"

  data:
    mongodb:
      uri: mongodb+srv://rodasenoc4_db_user:LVDqpURVaOZbfkQz@nnt-distributed-db.effpohk.mongodb.net/nnt-db?retryWrites=true&w=majority&appName=nnt-distributed-db

  redis:
    host: redis
    port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafka:9092}

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: transaction-processor-group
      auto-offset-reset: earliest
      enable-auto-commit: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    topics:
      - name: wallet.transfer.requested
        num-partitions: 3
        replication-factor: 1
      - name: wallet.topup.requested
        num-partitions: 3
        replication-factor: 1
      - name: transaction.processed
        num-partitions: 3
        replication-factor: 1
      - name: transaction.failed
        num-partitions: 3
        replication-factor: 1

  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.ms.transaction: DEBUG
    org.springframework.kafka: INFO